init:
  - git config --global core.autocrlf input

build:
  verbosity: detailed

environment:
  nodejs_version: "12.16.1"

cache:
  - "%LOCALAPPDATA%\\Yarn"

os: Visual Studio 2022

# Install scripts. (runs after repo cloning)
install:
  # .NET SDK 6.0.100 comes installed on the base image
  # - cmd: choco install dotnet-sdk --version 6.0.100
  # Get the latest stable version of Node.js
  - ps: Install-Product node $env:nodejs_version

  # # Update npm
  # # There seems to be issues with npm 5.4 in Windows
  # # See https://github.com/npm/npm/issues/18380
  # - npm install -g npm@6.1.0

build_script:
  - cmd: dotnet tool restore
  - cmd: dotnet run --project ./build/Build.fsproj -- BuildRunAllTests
  - cmd: dotnet run --project ./build/Build.fsproj -- IntegrationTests
  - cmd: dotnet run --project ./build/Build.fsproj -- IntegrationTestsNagareyama
  - cmd: dotnet run --project ./build/Build.fsproj -- IntegrationTestsNagareyamaV4

test: off
